management:
  endpoints:
    web:
      exposure:
        include:
        - beans
        - health
        - metrics
        - env
        - info

server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: account-service


