management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - metrics
          - env
          - info

server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: lesson-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
